### ISSUE TITLE
Samples hybrid-gke IAM Project ID bug

### ISSUE THREAD

**Issue by Red-Five** [apigee/terraform-modules#115]
https://github.com/apigee/terraform-modules/blob/main/samples/hybrid-gke/main.tf#L212

should read

`iam_project_roles = {
  "${module.project.project_id}" = [
    ...
  ]
}`

in order to extract the Project ID correctly from the module.

**Comment by danistrebel** [comment]
Hybrid provisioning has moved away from kustomize and on to helm. This is no longer applicable.
