### ISSUE TITLE
Support for environment types - PAYGv2

### ISSUE THREAD

**Issue by carlosmscabral** [apigee/terraform-modules#135]
With the new PAYGv2 pricing model, the environment object has changed to include a new parameter - EnvironmentType (https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments#environmenttype) . Also, for PAYGv2, nodes will become irrelevant (https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments#nodeconfig). I understand we depend on the upstream Google TF provider, but these changes might change some TF scripts, depending on what they are using/configuring.

**Comment by carlosmscabral** [comment]
I think this is solved know. I see it on the core provider - https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_environment . @danistrebel - I'll go ahead and close this issue!

**Comment by carlosmscabral** [comment]
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/apigee_environment

**Comment by danistrebel** [comment]
Thanks for the heads up @carlosmscabral once it's cascaded down to the CFF apigee module we can include it in our samples here.
