### ISSUE TITLE
Add Apigee X with multi-region (dual region) pattern

### ISSUE THREAD

**Issue by srs2210** [apigee/terraform-modules#18]
Client -> L7 XLB -> Proxy VM/Pods (Region 1) -> Apigee X (Runtime Instance Region 1)
Client -> L7 XLB -> Proxy VM/Pods (Region 2) -> Apigee X (Runtime Instance Region 2)

**Comment by danistrebel** [comment]
@srs2210 This should be fixed by the sample https://github.com/apigee/terraform-modules/tree/main/samples/x-multi-region that @daschwanden created and was merged in #17. 

Please reopen if you see any remaining gap in functionality.
