### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by nagendrasidgs** [apigee/terraform-modules#25]
It times out when creating the instance. Had to use gtimeout/timeout cmd. Please let me know if that's not the case with your testing.

Also, after the initial timeout, I wasn't able to delete the KMS keys and rest of the resource with 'destroy'. Had to create a new project for a fresh start.

**Comment by danistrebel** [comment]
Thanks for the heads up. 
I haven't observed or heard this yet so my best guess is that this might have been related to an intermittent issue.  Generally the creation of the instance returns within the timeout.

The timeout in the Apigee resource should be 60min according to this https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_apigee_instance.go#L38. If you observed additional latency then a new issue for the provider resource might be needed.

**Comment by danistrebel** [comment]
Closing this as there weren't any follow ups. Assuming it was a transient issue of the underlying API.
