### ISSUE TITLE
mTLS certificates error

### ISSUE THREAD

**Issue by pysiok1983** [apigee/terraform-modules#26]
Hi,
I am trying to use mTLS envoy and I generated a self-signed cert as follows:

`openssl req -newkey rsa:2048 -nodes -keyform PEM -keyout example-ca.key -x509 -days 3650 -outform PEM -out example-ca.crt
openssl genrsa -out example.key 2048
openssl req -new -key example.key -out example.csr
openssl x509 -req -in example.csr -CA example-ca.crt -CAkey example-ca.key -set_serial 100 -days 365 -outform PEM -out example.crt`

for envoy I am using:

`              common_tls_context:
                validation_context:
                  trusted_ca:
                    filename: /opt/apigee/certs/example-ca.crt
                tls_certificates:
                  - certificate_chain:
                      filename: /opt/apigee/certs/example.crt
                    private_key:
                      filename: /opt/apigee/certs/example.key`

for client:

`openssl genrsa -out example-cli.key 2048
openssl req -new -key example-cli.key -out example-cli.csr
openssl x509 -req -in example-cli.csr -CA example-ca.crt -CAkey example-ca.key -set_serial 101 -days 365 -outform PEM -out example-cli.crt`

For all certs I used "app1.test.com" as a FQDN. 

When I am trying to reach envoy from my internal VM I am receiving an error:

curl "https://app1.test.com/test" --cert example-cli.crt --key example-cli.key --cacert example.crt -vv

`* Expire in 3 ms for 1 (transfer 0x5619776d10f0)
*   Trying 10.100.0.28...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x5619776d10f0)
* Connected to app1.test.com (10.100.0.28) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: example.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, CERT verify (15):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd; CN=app1.test.com
*  start date: Mar 28 08:08:56 2022 GMT
*  expire date: Mar 28 08:08:56 2023 GMT
*  common name: app1.test.com (matched)
*  issuer: C=AU; ST=Some-State; O=Internet Widgits Pty Ltd; CN=app1.test.com
*  SSL certificate verify ok.
* SSL_write() returned SYSCALL, errno = 32
* Failed sending HTTP request
* Connection #0 to host app1.test.com left intact
curl: (55) SSL_write() returned SYSCALL, errno = 32`

`curl: (56) OpenSSL SSL_read: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca, errno 0`

**Comment by danistrebel** [comment]
Thanks for reaching out.

Are you able to validate that the example.crt/key and the ca are propagated correctly onto the envoy VMs?
They should be copied from the storage bucket to the VMs.

```sh
openssl x509 -in /opt/apigee/certs/example.crt  -purpose -noout -text
openssl x509 -in /opt/apigee/certs/example-ca.crt  -purpose -noout -text
```

Alternatively this blog post could give some additional context: https://www.googlecloudcommunity.com/gc/Cloud-Product-Articles/Network-and-Envoy-Proxy-Configuration-to-manage-mTLS-on-Apigee-X/ta-p/175146 (but your cert names match so maybe you already found it 😄 )

**Comment by pysiok1983** [comment]
Thank you for your comment. Yes, I generated following the webpage which you provided. Seems that path is wrong. The certs are stored in /var folder.

cacert:
`Certificate purposes:
SSL client : Yes
SSL client CA : Yes
SSL server : Yes
SSL server CA : Yes
Netscape SSL server : Yes
Netscape SSL server CA : Yes
S/MIME signing : Yes
S/MIME signing CA : Yes
S/MIME encryption : Yes
S/MIME encryption CA : Yes
CRL signing : Yes
CRL signing CA : Yes
Any Purpose : Yes
Any Purpose CA : Yes
OCSP helper : Yes
OCSP helper CA : Yes
Time Stamp signing : No
Time Stamp signing CA : Yes
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            01:ef:54:a7:45:73:52:ee:0a:f3:c8:01:2b:24:d1:c6:6a:d5:b3:b1
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = app1.test.com
        Validity
            Not Before: Mar 28 08:07:37 2022 GMT
            Not After : Mar 25 08:07:37 2032 GMT
        Subject: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = app1.test.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:bc:30:4b:65:09:65:71:03:f8:ba:a7:8f:08:79:
                    d1:af:73:be:b9:93:5b:b0:8d:1c:ef:04:45:e7:84:
                    a9:0c:27:74:d1:42:8c:7a:56:e4:92:74:48:e3:26:
                    8d:f6:33:be:09:51:a5:22:cf:38:66:de:41:64:00:
                    7b:92:96:51:5e:18:c5:e7:5c:ed:e8:8f:47:1b:cb:
                    7a:4c:c3:57:50:fa:f8:74:b5:5c:1b:37:91:49:e5:
                    e5:b1:cd:5f:04:62:e5:58:25:da:2e:06:5c:7e:39:
                    92:bd:e7:3b:8e:99:52:02:b0:ec:18:da:6a:56:82:
                    d0:c0:98:f4:a8:19:cb:55:b9:22:6b:02:b4:c4:84:
                    50:6c:bc:be:bd:df:ea:59:fe:0d:01:d0:50:14:89:
                    08:cf:9c:91:fe:1c:fe:36:6f:ef:ae:2a:1e:ad:1f:
                    43:92:71:7a:94:3e:41:d5:e1:63:34:d1:c6:5c:e4:
                    8e:fe:d2:0f:60:82:b9:55:ff:d0:50:0a:1e:db:1e:
                    35:06:ec:85:14:73:52:e4:40:1f:ed:21:a0:e0:ba:
                    a4:3b:24:23:72:a5:b9:4f:7a:b3:47:9b:26:58:b5:
                    db:36:2e:79:e3:25:84:10:7c:b4:6e:c8:4f:b6:18:
                    b3:06:f6:be:8e:a2:72:66:19:06:9f:21:2c:07:db:
                    8d:dd
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                CC:D0:E9:BA:83:2B:5F:E2:94:43:DF:79:22:7A:87:D6:5D:F6:56:9D
            X509v3 Authority Key Identifier: 
                keyid:CC:D0:E9:BA:83:2B:5F:E2:94:43:DF:79:22:7A:87:D6:5D:F6:56:9D

            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
         56:84:8f:ab:00:a0:b3:28:42:5f:7f:69:0a:72:55:14:92:d6:
         38:7d:ac:58:6f:af:af:b6:16:f5:5a:36:ef:77:82:c2:1c:35:
         db:2a:89:f8:64:db:f8:be:74:c0:f2:0b:db:19:ad:c8:2b:5b:
         30:09:ff:db:1b:31:ff:22:fe:4a:82:a3:a0:38:2c:4b:cf:77:
         c4:b3:7f:ff:ff:d9:3d:61:56:1d:3c:64:cc:88:cf:91:13:7f:
         c6:a1:28:d6:41:53:dd:08:08:99:d9:e8:4f:a4:0c:14:14:51:
         29:98:d8:af:93:2c:14:bd:4d:ac:09:c4:df:25:a4:55:86:e0:
         93:2e:c1:c0:f9:63:22:30:cf:21:28:a7:95:6e:08:e2:d5:4c:
         e0:22:d0:85:21:65:5e:fa:9c:bb:a7:eb:5c:60:59:da:af:cb:
         85:c2:c6:1e:ae:08:7c:4b:21:88:f5:89:3b:0d:0b:fa:0f:17:
         48:06:2b:d1:cf:dd:d8:de:55:fc:f2:c4:6c:46:82:08:37:25:
         1e:f0:77:09:17:f6:b2:67:4d:9d:59:17:c6:10:09:70:0b:77:
         8d:c5:71:94:4c:e4:45:b4:f5:f0:6b:59:d4:f2:12:c5:d7:7e:
         af:87:89:9b:0e:74:19:16:4c:cd:a9:b4:57:d6:c0:bc:4a:ee:
         34:dd:a9:54`

servercert:

`Certificate purposes:
SSL client : Yes
SSL client CA : Yes (WARNING code=3)
SSL server : Yes
SSL server CA : Yes (WARNING code=3)
Netscape SSL server : Yes
Netscape SSL server CA : Yes (WARNING code=3)
S/MIME signing : Yes
S/MIME signing CA : Yes (WARNING code=3)
S/MIME encryption : Yes
S/MIME encryption CA : Yes (WARNING code=3)
CRL signing : Yes
CRL signing CA : Yes (WARNING code=3)
Any Purpose : Yes
Any Purpose CA : Yes
OCSP helper : Yes
OCSP helper CA : Yes (WARNING code=3)
Time Stamp signing : No
Time Stamp signing CA : Yes (WARNING code=3)
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 100 (0x64)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = app1.test.com
        Validity
            Not Before: Mar 28 08:08:56 2022 GMT
            Not After : Mar 28 08:08:56 2023 GMT
        Subject: C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = app1.test.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:b7:53:83:9b:16:96:cc:d5:95:9f:3d:75:e4:8e:
                    62:c5:76:33:87:83:20:b7:d0:0d:f2:38:dd:fd:87:
                    b4:8c:2d:fc:f5:e1:0c:5e:cc:8a:96:57:62:a2:36:
                    b7:bb:d0:f7:a6:a7:2e:36:4f:de:c5:c7:3d:ff:5c:
                    f2:d9:5c:ea:28:15:b6:c2:a1:ee:8a:ac:06:5e:ac:
                    13:82:35:20:31:da:ef:1e:68:90:85:a7:43:03:e8:
                    f5:3e:33:8c:28:82:cc:08:72:88:c4:29:91:90:ea:
                    92:86:19:ee:d5:80:17:c7:80:1f:56:c0:c6:11:94:
                    aa:92:a5:d7:1f:bc:8a:c3:66:26:8f:1e:db:4d:cc:
                    cc:87:b7:0e:1c:16:6b:9c:03:9e:b3:00:d6:c6:54:
                    70:e4:90:25:c9:38:7c:2f:9a:c8:4d:d0:47:91:4e:
                    e3:ef:3e:90:9a:30:d6:fd:38:5f:5b:bc:80:f1:cd:
                    e3:3c:ab:df:84:6f:1d:f7:fd:e0:b2:ed:12:a8:b3:
                    dd:4a:91:f7:48:98:61:f5:83:ec:f0:d0:1f:b7:64:
                    db:75:24:ed:4a:8d:8e:eb:02:00:1d:ea:0c:60:6e:
                    0c:f6:79:e6:ef:9a:c0:32:a1:29:ba:f6:2a:30:95:
                    4a:d2:d0:a4:32:d1:f1:69:2c:ce:7c:04:91:cf:3e:
                    f1:e7
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
         97:53:45:43:5a:9e:59:ef:7b:29:f9:0f:b2:64:2e:c2:c9:51:
         2d:b9:b3:df:78:84:9c:d4:88:0a:b0:e1:4e:af:48:09:0b:1e:
         1f:3e:6f:b6:b7:3c:92:47:0a:5a:e6:44:d9:e3:78:e9:3e:7e:
         e6:bd:7b:96:b3:eb:64:11:82:3b:d0:53:e1:43:e9:c2:52:2d:
         f5:fb:3e:1d:a1:11:c7:f3:ec:f7:91:c3:b6:76:05:34:49:28:
         f1:63:f2:1a:32:8f:0c:65:86:d8:16:aa:54:e5:f6:d8:57:d5:
         4a:7c:fc:95:fb:9e:05:8d:96:0e:b3:c3:2e:a5:1b:dc:a9:26:
         27:47:e4:d1:29:03:f0:c3:38:66:4f:00:56:4e:d7:0b:16:6f:
         1e:71:03:a8:ea:50:6a:ef:4a:8b:95:ba:37:d0:90:b0:25:64:
         7e:de:cf:3f:ab:88:1d:17:6a:7b:e7:01:57:4e:13:a4:83:5d:
         a7:3f:12:b4:bc:d6:0a:4a:96:ad:17:1b:ef:ce:19:a8:23:67:
         fe:86:52:a0:21:a0:fe:a6:15:50:a4:53:b0:0c:9a:e0:c4:55:
         5e:9b:c3:b3:8b:a5:67:f5:bb:b0:8f:07:41:b6:21:26:06:ab:
         e8:47:27:d7:f2:fc:cb:d7:9f:51:6d:a0:56:92:c7:9d:35:db:
         59:66:b6:f8`

**Comment by pysiok1983** [comment]
ls -la for opt

drwxr-xr-x  3 root root 4096 Mar 28 17:25 .
drwxr-xr-x 18 root root 4096 Mar 28 17:24 ..
drwx--x--x  4 root root 4096 Mar 28 17:25 containerd

**Comment by danistrebel** [comment]
I validated it in my project and it worked fine.

**Comment by pysiok1983** [comment]
thank you - one Q - I thought we have to use "root cert" as a CA for signing the server and client cert. Seems that this is not required - am I right?

**Comment by danistrebel** [comment]
Yeah I saw in your script. I opted to use different CAs such that a compromised server cert can't be used in a client auth. From a similar point of view in production you'll most likely want to limit the purposes of each CA/cert.

**Comment by pysiok1983** [comment]
Thank you. One more question. Can you explain a use case for "X with DNS peering"? Is it part of PSC configuration? When should I use this DNS peering? I assume this will not help if my backend is hosted in VPC which does not peer to the APIgee - am I right?

**Comment by danistrebel** [comment]
DNS peering is used to allow you to use your Cloud DNS Zone in Apigee. It's not directly related to PSC but it should be usable with PSC as well. 

Basic Idea: 
1. Create an SB PSC attachment in Apigee -> this gives you a PUPI IP address like 7.0.0.2
2. Create a private DNS zone like backends.internal and an A record for foo.backends.internal pointing to 7.0.0.2
3. Use foo.backends.internal as the hostname in your target sever.

**Comment by pysiok1983** [comment]
So the idea is to have a public IP (7.0.0.2) that can be used from anywhere (due to the fact that this traffic destined for API runtime is going over the Internet). Am I right? What do you mean by "SB PSC"?  
Target server - do you mean virtual host within APIgee?

**Comment by danistrebel** [comment]
Sorry, I think I got you confused. SB PSC is [Southbound Private Service Connect](https://cloud.google.com/apigee/docs/api-platform/architecture/southbound-networking-patterns-endpoints). It's is implemented in Apigee to use a [PUPI](https://cloud.google.com/architecture/configuring-privately-used-public-ips-for-GKE) but that's an internal concern. The traffic stays local but is using an IP range that is outside of the RFC 1918 range to preserve the number of available IPs.

Virtual hosts are used for the northbound connectivity (clients calling Apigee.).

@pysiok1983 If you have additional questions I'd suggest we move this to the Apigee community forum such that it is better visible for others that might have the same questions in the future.

**Comment by pysiok1983** [comment]
@danistrebel Thank you, Daniel. One more question regarding the certificate. How can I add a new domain to the certificate (FQDN)? For instance, I have app1.myapp.com and I would like to also have app1.yourapp.com. Can I sue just "*" as an FQDN for envoy cert?

**Comment by danistrebel** [comment]
Sure, on the server cert you can either use a wildcard cert or a cert with [SAN](https://en.wikipedia.org/wiki/Subject_Alternative_Name)s for the different domains.

**Comment by danistrebel** [comment]
Closing this as it seems resolved.
