### ISSUE TITLE
KMS key Ring key rotation

### ISSUE THREAD

**Issue by nagspace** [apigee/terraform-modules#43]
I don't see the KMS keys are going through rotation or a value is set to enable that. Will ApigeeX support the KMS key rotation if we chance the module from apigee-x-core ?

**Comment by danistrebel** [comment]
Thanks for the comment. KMS rotation is definitely possible. I just created a PR to include a default rotation of 30 days in the core module. This is backwards compatible meaning if you upgrade to the latest module version it will update the rotation period of your keys (set module variable to `null` if you wish to keep the current behavior for what ever reason.)
