### ISSUE TITLE
Add support in L7 Load Balancer Configuration for security_policy field

### ISSUE THREAD

**Issue by justin-watkinson-cherre** [apigee/terraform-modules#60]
In order to associate Cloud Armor security configurations with the layer 7 load balancer created by the [mig-x7xlb module](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service), we would need to add a parameter not currently present in this module's interface.

To implement this, we would need to have access to define a variable to populate the [security_policy](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service#security_policy) field in the [compute_backend_service](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_service) resource.

This use case may be common enough to consider supporting at this level without the need to fork or create other workarounds.

**Comment by danistrebel** [comment]
Thanks Justin, great suggestion. Added and released in module version [0.5.0](https://github.com/apigee/terraform-modules/releases/tag/v0.5.0)
