### ISSUE TITLE
Not able to configure "Access Routing" through terraform module/s

### ISSUE THREAD

**Issue by harishtallam** [apigee/terraform-modules#66]
Hi,

I have tried executing the below sample terraform code to provision ApigeeX evaluation stack. But, I notice that "Access Routing" is not being configured on executing this. Am I missing something? Please suggest.

[https://github.com/apigee/terraform-modules/tree/main/samples/x-l7xlb](url)

Attached are screenshots and terraform logs for reference.
<img width="466" alt="access_routing_1" src="https://user-images.githubusercontent.com/74064024/192078029-00cc518c-e764-4916-bdfd-7c2a97d7406c.PNG">
<img width="389" alt="access_routing_2" src="https://user-images.githubusercontent.com/74064024/192078031-ed6886ee-0399-415c-b2eb-822fa39c7c75.PNG">
[terraform_apply_output.txt](https://github.com/apigee/terraform-modules/files/9637834/terraform_apply_output.txt)

**Comment by danistrebel** [comment]
Hi @harishtallam, The in your output it shows that it was successful in creating an external HTTPS load balancer:

```
module.mig-l7xlb.google_compute_backend_service.mig_backend: Creating...
module.mig-l7xlb.google_compute_backend_service.mig_backend: Still creating... [10s elapsed]
module.mig-l7xlb.google_compute_backend_service.mig_backend: Still creating... [20s elapsed]
module.mig-l7xlb.google_compute_backend_service.mig_backend: Still creating... [30s elapsed]
module.mig-l7xlb.google_compute_backend_service.mig_backend: Creation complete after 34s [id=projects/nth-honor-363415/global/backendServices/apigee-xlb-backend]
module.mig-l7xlb.google_compute_url_map.url_map: Creating...
module.mig-l7xlb.google_compute_url_map.url_map: Still creating... [10s elapsed]
module.mig-l7xlb.google_compute_url_map.url_map: Creation complete after 12s [id=projects/nth-honor-363415/global/urlMaps/apigee-xlb]
module.mig-l7xlb.google_compute_target_https_proxy.https_proxy: Creating...
module.mig-l7xlb.google_compute_target_https_proxy.https_proxy: Still creating... [10s elapsed]
module.mig-l7xlb.google_compute_target_https_proxy.https_proxy: Creation complete after 12s [id=projects/nth-honor-363415/global/targetHttpsProxies/apigee-xlb-target-proxy]
module.mig-l7xlb.google_compute_global_forwarding_rule.forwarding_rule: Creating...
module.mig-l7xlb.google_compute_global_forwarding_rule.forwarding_rule: Still creating... [10s elapsed]
module.mig-l7xlb.google_compute_global_forwarding_rule.forwarding_rule: Creation complete after 12s [id=projects/nth-honor-363415/global/forwardingRules/apigee-xlb-forwarding-rule]
```

You might not see it in the UI as the UI logic might look for other components. Regardless the internet facing access should be enabled and ready for you to use.

**Comment by danistrebel** [comment]
I'll close this assuming the answer provided an answer to your question. Please feel free to follow up if you still cannot see the XLB that the module created.
