### ISSUE TITLE
Apigee Integration is not shown in the Apigee console.

### ISSUE THREAD

**Issue by mrzkhd** [apigee/terraform-modules#72]
Hi, I have set up the Apigee using the provided modules and the L7XLB module to have a load balancer. Everything is fine so far; the only issue is that the **Integration** section in the **Develop** menu is unavailable. So just wondering if you know what's the answer to that.
Thanks.

**Comment by danistrebel** [comment]
Hi @mrzkhd, Apigee integration is no longer automatically deployed with Apigee X. Futhermore the integration product can now be deployed independently of Apigee X as described here: https://www.googlecloudcommunity.com/gc/Apigee/Now-available-to-try-Application-Integration-and-Integration/m-p/473002#M72356
