### ISSUE TITLE
Northbound PSC sample failing on initial apply

### ISSUE THREAD

**Issue by eddern** [apigee/terraform-modules#78]
Had an issue running `samples/x-nb-psc-xlb` on a newly formed GCP project. Terraform failed due to the `default` subnetwork already existing. 
![Screenshot 2022-10-26 at 14 42 59](https://user-images.githubusercontent.com/9265874/198034470-0addb6b7-81ca-42e7-9405-cadf8850fb0f.png)

Unsure if this subnet exists in every new GCP project, but removing the creation of the `vpc-ingress` module in the sample fixed it in my case (see [commit](https://github.com/eddern/terraform-modules/pull/2/commits/401822bd6a1faff586cdd6d269e6348979c8dd56))

**Comment by danistrebel** [comment]
Hi @eddern, thanks for the report. At the time of writing there was a limitation on PSC Neg TF provider that allowed only for the default network to be used. We decided to make the usage of the default network explicit and remove it just like you did if it already exists for them.

I'll validate if the default network restriction still applies and will either:
* Use a non-default network in the sample
* Explain the default network constraint in the readme.

**Comment by eddern** [comment]
Sounds good 👍

**Comment by danistrebel** [comment]
I validated the `default` network constraint on the PSC NEG and it does no longer apply. 
I hence refactored the example to use a non-default network for PSC ingress.
